cinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.url'))
]

ticketing/urls.py
from django.urls import path
from ticketing import views

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list, name='movie_list'),
    path('movie/details/<int:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/list/', views.cinema_list, name='cinema_list'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('showtime/details/<int:showtime_id>/', views.showtime_details, name='showtime_details'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
]

ticketing/models.py
from django.db import models

class Movie (models.Model):
    """
    Movie information and connections
    """
    class Meta:
        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم'
    name = models.CharField('عنوان', max_length=100)
    director = models.CharField('کارگردان', max_length=100)
    year = models.IntegerField('سال تولید')
    length = models.IntegerField('مدت زمان')
    description = models.TextField('توضیحات')

    def __str__(self):
        return self.name

class Cinema (models.Model):
    """
    Cinema information and connections
    """
    class Meta:
        verbose_name = 'سینما'
        verbose_name_plural = 'سینما'
    cinema_code = models.IntegerField('کد سینما', primary_key=True)
    name = models.CharField('نام سینما', max_length=50)
    city = models.CharField('شهر', max_length=100, default='تهران')
    capacity = models.IntegerField('ظرفیت')
    phone = models.CharField('شماره تماس', max_length=50, null=True)
    address = models.TextField('آدرس')

    def __str__(self):
        return self.name

class Showtime (models.Model):
    """
    Connecting between Cinema and Movie
    """
    class Meta:
        verbose_name = 'سانس'
        verbose_name_plural = 'سانس'
    movie = models.ForeignKey('Movie', on_delete=models.PROTECT, verbose_name='فیلم')
    cinema = models.ForeignKey('Cinema', on_delete=models.PROTECT, verbose_name='سینما')

    start_time = models.DateTimeField('زمان شروع نمایش')
    price = models.IntegerField('قیمت')
    salable_seats = models.IntegerField('صندلی های قابل فروش')
    free_seats = models.IntegerField('صندلی های خالی')

    SALE_NOT_STARTED = 1
    SALE_OPEN = 2
    TICKETS_SOLD = 3
    SALE_CLOSED = 4
    MOVIE_PLAYED = 5
    SHOW_CANCELED = 6
    status_choices = (
        (SALE_NOT_STARTED, 'فروش آغاز نشده'),
        (SALE_OPEN, 'در حال فروش بلیت'),
        (TICKETS_SOLD, 'بلیت ها تمام شد'),
        (SALE_CLOSED, 'فروش بلیت بسته شد'),
        (MOVIE_PLAYED, 'فیلم پخش شد'),
        (SHOW_CANCELED, 'سانس لغو شد'),
    )
    status = models.IntegerField('وضعیت', choices=status_choices)

    def __str__(self):
        return '{} - {} - {}'.format(self.movie, self.cinema, self.start_time)

    def reserve_seats(self, seat_count):
        assert isinstance(seat_count, int) and seat_count > 0, 'number of seats show'
        assert self.status == Showtime.SALE_OPEN, 'sale is not open'
        assert self.free_seats >= seat_count, 'not enough free seats'
        self.free_seats -= seat_count
        if self.free_seats == 0:
            self.status = Showtime.TICKETS_SOLD
        self.save()

class Ticket(models.Model):
    class Meta:
        verbose_name = 'بلیت'
        verbose_name_plural = 'بلیت'

    showtime = models.ForeignKey('Showtime', on_delete=models.PROTECT, verbose_name='سانس')
    customer = models.ForeignKey('accounts.Profile', on_delete=models.PROTECT, verbose_name='خریدار')
    seat_count = models.IntegerField('تعداد صندلی')
    order_time = models.DateTimeField('زمان خرید', auto_now_add=True)

    def __str__(self):
        return '{} بلیت به نام {} برای فیلم {}'.format(self.seat_count, self.customer, self.showtime)

ticketing/forms.py
from django import forms

from ticketing.models import Cinema


class ShowTimeSearchForm(forms.Form):
    movie_name = forms.CharField(max_length=100, label='نام فیلم', required=False)
    sale_is_open = forms.BooleanField(label='فقظ سانس های قابل خرید', required=False)
    movie_length_min = forms.IntegerField(label='حداقل زمان فیلم', min_value=0, max_value=500, required=False)
    movie_length_max = forms.IntegerField(label='حداکثر زمان فیلم', min_value=0, max_value=500, required=False)

    PRICE_ANY = '0'
    PRICE_UNDER_10 = '1'
    PRICE_10_TO_15 = '2'
    PRICE_15_TO_20 = '3'
    PRICE_ABOVE_20 = '4'
    PRICE_LEVEL_CHOICES = (
        (PRICE_ANY, 'هر قیمتی'),
        (PRICE_UNDER_10, 'تا 10 هزار تومان'),
        (PRICE_10_TO_15, '10 تا 15 هزار تومان'),
        (PRICE_15_TO_20, '15 تا 20 هزار تومان'),
        (PRICE_ABOVE_20, 'بیش از 20 هزار تومان'),
    )
    price_level = forms.ChoiceField(label='محدوده قیمت', choices=PRICE_LEVEL_CHOICES, required=False)
    cinema = forms.ModelChoiceField(label='سینما', queryset=Cinema.objects.all(), required=False)

    def get_price_boundries(self):
        price_level = self.cleaned_data['price_level']
        if price_level == ShowTimeSearchForm.PRICE_UNDER_10:
            return None, 10000
        elif price_level == ShowTimeSearchForm.PRICE_10_TO_15:
            return 10000, 15000
        elif price_level == ShowTimeSearchForm.PRICE_15_TO_20:
            return 15000, 20000
        elif price_level == ShowTimeSearchForm.PRICE_ABOVE_20:
            return 20000, None
        else:
            return None, None

ticketing/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from ticketing.forms import ShowTimeSearchForm
from ticketing.models import Movie, Cinema, Showtime, Ticket


def movie_list(request):
    movies = Movie.objects.all()
    count = len(movies)
    context = {
        'movie_list': movies,
        'movie_count': count
    }
    return render(request, 'ticketing/movie_list.html', context)

def cinema_list(request):
    cinemas = Cinema.objects.all()
    context = {
        'cinemas': cinemas
    }
    return render(request, 'ticketing/cinema_list.html', context)

def movie_details(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    context = {
        'movie': movie
    }
    return render(request, 'ticketing/movie_details.html', context)

def cinema_details(request, cinema_id):
    cinema = get_object_or_404(Cinema, pk=cinema_id)
    context = {
        'cinema': cinema
    }
    return render(request, 'ticketing/cinema_details.html', context)


def showtime_list(request):
    search_form = ShowTimeSearchForm(request.GET)
    showtimes = Showtime.objects.all()
    if search_form.is_valid():
        showtimes = Showtime.objects.filter(movie__name__contains=search_form.cleaned_data['movie_name'])
        if search_form.cleaned_data['sale_is_open']:
            showtimes = showtimes.filter(status=Showtime.SALE_OPEN)
        if search_form.cleaned_data['movie_length_min'] is not None:
            showtimes = showtimes.filter(movie__length__gte=search_form.search_form.cleaned_data['movie_length_min'])
        if search_form.cleaned_data['movie_length_max'] is not None:
            showtimes = showtimes.filter(movie__length__lte=search_form.search_form.cleaned_data['movie_length_max'])
        if search_form.cleaned_data['cinema'] is not None:
            showtimes = showtimes.filter(cinema=search_form.cleaned_data['cinema'])
        min_price, max_price = search_form.get_price_boundries()
        if min_price is not None:
            showtimes = showtimes.filter(price__gt=min_price)
        if max_price is not None:
            showtimes = showtimes.filter(price__lte=max_price)

    showtimes = showtimes.order_by('start_time')
    context = {
        'showtimes': showtimes,
        'search_form': search_form
    }
    return render(request, 'ticketing/showtime_list.html', context)

@login_required
def showtime_details(request, showtime_id):
    showtime = Showtime.objects.get(pk=showtime_id)
    context = {
        'showtime': showtime
    }
    if request.method == 'POST':
        try:
            seat_count = int(request.POST['seat_count'])
            assert showtime.status == Showtime.SALE_OPEN, 'خرید این بلیت برای این سانس ممکن نیست'
            assert showtime.free_seats >= seat_count, 'به میزان انتخابی صندلی خالی وجود ندارد'
            total_price = showtime.price * seat_count
            assert request.user.profile.spend(total_price), 'موجودی کافی نیست'
            showtime.reserve_seats(seat_count)
            ticket = Ticket.objects.create(showtime=showtime, customer=request.user.profile, seat_count=seat_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reversed('ticketing:ticket_details', kwargs={'ticket_id': ticket.id}))
        return render(request, 'ticketing/showtime_details.html', context)

@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(customer=request.user.profile).order_by('-order_time')
    context = {
       'tickets': tickets
    }
    return render(request, 'ticketing/ticket_list.hyml', context)

@login_required
def ticket_details(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    context = {
        'ticket': ticket
    }
    return render(request, 'ticketing/ticket_details.html', context)

ticketing/templates/ticketing/cinema_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ cinema.name }} </title>
</head>
<body>
    <p>
        نام سینما:
        {{ cinema.name }}
    </p>
    <p>
        شهر:
        {{ cinema.city }}
    </p>
    <p>
         ظرفیت:
        {{ cinema.capacity }}
    </p>
    <p>
        شماره تماس:
        {{ cinema.phone }}
    </p>
    <p>
        آدرس:
        {{ cinema.address }}
    </p>
</body>
</html>

ticketing/templates/ticketing/cinema_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>لیست سینما ها</title>
</head>
<body>
    <h1>سامانه فروش بلیت</h1>
    <h2>سینما های فعال</h2>
    <a href="{% url 'ticketing:movie_list' %}">
        برای دیدن فیلم ها کلیک کنید
    </a>
    {% if cinemas %}
        <ul>
         {% for cinema in cinemas %}
            <li>
            <a href="{% url "ticketing:cinema_details" cinema_id=cinema.cinema_code %}">
            {{ cinema }}
            </a>
            </li>
         {% endfor %}
        </ul>
    {% else %}
        <p style="color: red">
            متاسفانه سینمایی وجود ندارد
        </p>
    {% endif %}

</body>
</html>

ticketing/templates/ticketing/movie_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.name }} </title>
</head>
<body>
    <p>
        نام فیلم:
        {{ movie.name }}
    </p>
    <p>
        کارگردان:
        {{ movie.director }}
    </p>
    <p>
        سال تولید:
        {{ movie.year }}
    </p>
    <p>
        مدت زمان:
        {{ movie.length }}
    </p>
    <p>
        توضیحات:
        {{ movie.description }}
    </p>
</body>
</html>

ticketing/templates/ticketing/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>لیست فیلم ها</title>
</head>
<body>
    <h1>سامانه فروش بلیت</h1>
    <h2>فیلم های در حال اکران</h2>
    <a href="{% url 'ticketing:cinema_list' %}">
        برای دیدن سینما ها کلیک کنید
    </a>
    {% if movie_list %}
        <p style="color: green">
        تعداد
        {{ movie_count }}
        فیلم وجود دارد
        </p>
        <ul>
         {% for movie in movie_list %}
            <li>
            <a href="{% url "ticketing:movie_details" movie_id=movie.id %}">
            {{ movie }}
            </a>
            </li>
         {% endfor %}
        </ul>
    {% else %}
        <p style="color: red">
            متاسفانه فیلیمی وجود ندارد
        </p>
    {% endif %}

</body>
</html>

ticketing/templates/ticketing/showtime_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ticketing/templates/ticketing/showtime_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ticketing/templates/ticketing/ticket_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ticketing/templates/ticketing/ticket_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>